export const products = [
  {
    id: 1,
    title: "야구공",
    price: 5000,
    img: "/src/assets/img/baseball.png",
    desc: "박찬호 싸인 야구공",
    seller: "user1",
    storage: 5,
  },
  {
    id: 2,
    title: "럭비공",
    price: 45000,
    img: "/src/assets/img/rugbyball.png",
    desc: "미국에서 구한 럭비공",
    seller: "user2",
    storage: 10,
  },
  {
    id: 3,
    title: "축구공",
    price: 30000,
    img: "/src/assets/img/soccerball.png",
    desc: "박지성이 사용했던 축구공",
    seller: "user2",
    storage: 3,
  },
  {
    id: 4,
    title: "배구공",
    price: 40000,
    img: "/src/assets/img/volleyball.png",
    desc: "김연경이 사용했던 배구공",
    seller: "user3",
    storage: 1,
  },
  {
    id: 5,
    title: "테니스공",
    price: 15000,
    img: "/src/assets/img/tennisball.png",
    desc: "한정판 테니스공 4개입",
    seller: "user4",
    storage: 7,
  },
  {
    id: 6,
    title: "농구공",
    price: 33000,
    img: "/src/assets/img/basketball.png",
    desc: "마이클 조던이 사용한 전설의 농구공",
    seller: "user4",
    storage: 2,
  },
];
